<a href="https://colab.research.google.com/github/raviteja777/neural_network_demos/blob/master/keras_iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <center> IRIS data classification using Keras NN </center>

In [ ]:
from keras.models import Sequential

from keras.layers import Dense
from keras.utils import to_categorical

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

Using TensorFlow backend.


In [ ]:
#init dataset - load iris used from sklearn
iris = load_iris()

In [ ]:
# get the data description
print(iris['DESCR'],sep="\n")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
# Divide into training and test sets

X_train,X_test,y_train,y_test = train_test_split(iris['data'],iris['target'],test_size=0.3,random_state=1234)

In [ ]:
print("train :\n",X_train[:5])
print("target :\n",y_train[:5])

train :
 [[4.9 3.1 1.5 0.1]
 [5.8 2.8 5.1 2.4]
 [6.7 3.  5.2 2.3]
 [7.7 3.  6.1 2.3]
 [6.7 3.1 5.6 2.4]]
target :
 [0 2 2 2 2]


In [ ]:
print("X_train shape {}".format(X_train.shape))
print("y_train shape {}".format(y_train.shape))
      

X_train shape (105, 4)
y_train shape (105,)


In [ ]:
# init model

model = Sequential()

W0624 07:06:51.272335 140447579133824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [ ]:
# provide a sequential model
#input = 5 , hidden = 0 , output=3

model.add(Dense(activation='relu',input_dim=4,units=5))
model.add(Dense(activation='softmax',units=3))

W0624 07:06:51.316998 140447579133824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0624 07:06:51.325201 140447579133824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

W0624 07:06:51.358485 140447579133824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0624 07:06:51.384536 140447579133824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [ ]:
# convert target variable  to categorical for eg:  class 1 convert --> 0 0 1 , class 2 -- 0 1 0 , class 3 - 1 0 0 

y_train_cat = to_categorical(y_train, num_classes=None)
y_test_cat = to_categorical(y_test, num_classes=None)

In [ ]:
print(X_train[:5],y_train_cat[:5],sep="\n")

[[4.9 3.1 1.5 0.1]
 [5.8 2.8 5.1 2.4]
 [6.7 3.  5.2 2.3]
 [7.7 3.  6.1 2.3]
 [6.7 3.1 5.6 2.4]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [ ]:
# fit the model with training data
model.fit(X_train,y_train_cat,epochs=20,batch_size=10)

W0624 07:06:51.520101 140447579133824 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0624 07:06:51.573041 140447579133824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/20
105/105 [==============================] - 0s 1ms/step - loss: 1.2635 - acc: 0.2762
Epoch 2/20
105/105 [==============================] - 0s 119us/step - loss: 1.0364 - acc: 0.2571
Epoch 3/20
105/105 [==============================] - 0s 119us/step - loss: 0.9383 - acc: 0.3714
Epoch 4/20
105/105 [==============================] - 0s 120us/step - loss: 0.8505 - acc: 0.5905
Epoch 5/20
105/105 [==============================] - 0s 132us/step - loss: 0.7864 - acc: 0.6286
Epoch 6/20
105/105 [==============================] - 0s 138us/step - loss: 0.7441 - acc: 0.6000
Epoch 7/20
105/105 [==============================] - 0s 120us/step - loss: 0.6958 - acc: 0.6667
Epoch 8/20
105/105 [==============================] - 0s 128us/step - loss: 0.6641 - acc: 0.6381
Epoch 9/20
105/105 [==============================] - 0s 133us/step - loss: 0.6357 - acc: 0.6476
Epoch 10/20
105/105 [==============================] - 0s 140us/step - loss: 0.6153 - acc: 0.6476
Epoch 11/20
105/105 [==========

In [ ]:
# get the performance metrics

loss_and_metrics = model.evaluate(X_test, y_test_cat, batch_size=10)

loss_and_metrics

45/45 [==============================] - 0s 628us/step


[0.5095561775896285, 0.6444444590144687]

In [ ]:
classes = model.predict(X_test, batch_size=10)

In [ ]:
classes

array([[0.0420947 , 0.44071695, 0.5171883 ],
       [0.03805044, 0.4496712 , 0.5122784 ],
       [0.02235049, 0.42912284, 0.54852664],
       [0.90265876, 0.02965333, 0.0676879 ],
       [0.06709595, 0.40657347, 0.5263306 ],
       [0.8513192 , 0.05153176, 0.09714909],
       [0.9182258 , 0.02511836, 0.05665584],
       [0.92882264, 0.02167211, 0.04950528],
       [0.05605891, 0.43500727, 0.50893384],
       [0.00898191, 0.46319458, 0.5278235 ],
       [0.07180368, 0.42916816, 0.4990282 ],
       [0.8953868 , 0.03395305, 0.0706601 ],
       [0.0133428 , 0.39328763, 0.59336954],
       [0.05745999, 0.40333965, 0.5392004 ],
       [0.88809794, 0.03078246, 0.08111964],
       [0.12418113, 0.40085223, 0.47496665],
       [0.02261183, 0.32574037, 0.6516478 ],
       [0.8420297 , 0.05609692, 0.10187343],
       [0.01614817, 0.45863146, 0.5252204 ],
       [0.05135938, 0.443     , 0.5056407 ],
       [0.05532736, 0.4362753 , 0.50839734],
       [0.03838446, 0.439388  , 0.5222275 ],
       [0.

In [ ]:
# predict categories

pred_cat = [np.where(item==np.max(item))[0][0] for item in classes ]

In [ ]:
disp = zip(y_test,pred_cat)
print(*tuple(disp),sep="\n")

(1, 2)
(1, 2)
(2, 2)
(0, 0)
(1, 2)
(0, 0)
(0, 0)
(0, 0)
(1, 2)
(2, 2)
(1, 2)
(0, 0)
(2, 2)
(1, 2)
(0, 0)
(1, 2)
(2, 2)
(0, 0)
(2, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 1)
(2, 2)
(0, 0)
(2, 2)
(1, 2)
(2, 2)
(0, 0)
(1, 2)
(2, 2)
(0, 0)
(2, 2)
(1, 2)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 2)
(0, 0)
(1, 2)
(0, 0)
(2, 2)
(2, 2)
